"""add gate_matrix table

Revision ID: b4e73e8526ba
Revises: 8bbb9de4301d
Create Date: 2026-07-20 12:03:14.503121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e73e8526ba'
down_revision: Union[str, Sequence[str], None] = '8bbb9de4301d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_matrix',
    sa.Column('matrix_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('function_type', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('exemption_note', sa.String(), nullable=True),
    sa.Column('risk_code', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('matrix_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gate_matrix')
    # ### end Alembic commands ###
