"""add correction_rules table

Revision ID: c6fd133b8e9e
Revises: b4e73e8526ba
Create Date: 2026-07-20 13:09:23.245847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6fd133b8e9e'
down_revision: Union[str, Sequence[str], None] = 'b4e73e8526ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('risky_text', sa.String(), nullable=False),
    sa.Column('safe_text', sa.String(), nullable=False),
    sa.Column('regulatory_score', sa.Integer(), nullable=False),
    sa.Column('privacy_score', sa.Integer(), nullable=False),
    sa.Column('advertising_score', sa.Integer(), nullable=False),
    sa.Column('derived_from_keyword_id', sa.UUID(), nullable=True),
    sa.Column('legal_basis_doc', sa.String(), nullable=False),
    sa.Column('legal_basis_article', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['derived_from_keyword_id'], ['gate_keywords.keyword_id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.rule_version_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correction_rules')
    # ### end Alembic commands ###
